### ISSUE TITLE
link no longer works

### ISSUE THREAD

**Issue by zschutzman** [gerrymandr/metagraph#20]
The url [mggg.org/metagraph](mggg.org/metagraph) no longer points to the project. Is this a problem with my code or is it something further up the hosting ladder?

@maxhully

**Comment by maxhully** [comment]
Ack, thanks for catching that. I just switched us from GitHub pages to
Netlify but forgot to migrate this.

**Comment by maxhully** [comment]
As a temporary fix it'll be up at https://gerrymandr.github.io/metagraph/ . On Monday I'll figure out the right way to get it on the mggg.org domain again.

**Comment by maxhully** [comment]
Lol! Good thing I set up the redirect this morning, because Gridlandia [got mentioned in Bustle](https://www.bustle.com/p/how-to-fight-gerrymandering-so-that-every-vote-you-cast-counts-for-something-16990761) at almost the exact same time.

**Comment by maxhully** [comment]
The link works now! For any future changes we should use the @mggg/metagraph repository.
